#version: '3.3'

networks:
  crm_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1


services:
  ################################################
  crm-test-apache:
    build:
      context: configs/apache/
      dockerfile: Dockerfile
      args:
        - APP_ENVIRONMENT=${APP_ENVIRONMENT}
    container_name: crm-test-apache
    restart: unless-stopped
    ports:
      - ${APACHE_EXTERNAL_HTTP_PORT}:80
      - ${APACHE_EXTERNAL_HTTPS_PORT}:443
    volumes:
      - ./configs/php/php.ini:/etc/php5/apache2/php.ini
      - ./../app:/home/www
      - ./configs/apache/run.sh:/run.sh
      #- ./configs/apache/conf-5.3.29-init:/etc/apache2
      - ./configs/apache/conf-5.3.29-test:/etc/apache2
      #- ./configs/apache/conf-5.3.29:/etc/apache2
      - ./configs/apache/usr_sbin/apache2-systemd-ask-pass:/usr/sbin/apache2-systemd-ask-pass
      - ./configs/apache/usr_share_apache2-mod_security2:/usr/share/apache2-mod_security2
      - ./configs/apache/usr_local_apache2:/usr/local/apache2
    networks:
      crm_net:
        ipv4_address: 10.5.0.6
    # the problem is: a lot of scripts have hardcoded localhost connection to mysql, and we cannot change them all,
    # but mysql in another docker container, so I need somehow forward localhost:3306 to 10.5.0.5:3306
    # iptables -F -t nat
    # iptables -t nat -A OUTPUT -o lo -p tcp --dport 3306 -j DNAT --to-destination 10.5.0.5:3306
    # iptables -A POSTROUTING -t nat -j MASQUERADE
    # but problem is deeper and forwarding doesn't help, because mysqli('localhost', 'user', 'pass' ...
    # tell to php to use socket but not tcp-connection
    # in this case I need to install in this docker software <<socat>> and make forwarding local socket to tcp 10.5.0.5:3306
    # like this command: `socat UNIX-LISTEN:/tmp/mysql.sock,fork,reuseaddr,unlink-early,user=root,group=root,mode=777 TCP:10.5.0.5:3306`
    # see .docker-from-my/configs/apache/run.sh
    # also I need to set sockets in php.ini (mysqli.default_socket =, pdo_mysql.default_socket=, mysql.default_socket =)
    #
    # this option add additional records into /etc/hosts which is in docker-container machine
    #extra_hosts:
    #  - "host-name:10.5.0.5"
    #
    # these options enable you to work with iptables.
    # but as I described before not need to use it, but need use <<socat>>
    #cap_add:
    #  - NET_ADMIN
    #  - ALL
    #
    # these options allow manage some /proc/sys parameters for docker-container machine
    # without specific parameters, iptables will not function correctly.
    #sysctls:
    #  - net.ipv4.ip_forward=1
    #  - net.ipv4.conf.all.route_localnet=1
    #  - net.ipv6.conf.lo.disable_ipv6=1
  ################################################
  crm-test-mysql:
    #image: mysql:8.0
    image: mysql/mysql-server:5.7
    container_name: crm-test-mysql
    restart: unless-stopped
    command:
      --default-authentication-plugin=mysql_native_password
      --innodb_use_native_aio=0
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    volumes:
      - ./configs/mysql/my.cnf:/etc/my.cnf
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-backups:/mysql-backups
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_USER_HOST=${MYSQL_USER_HOST}
    networks:
      crm_net:
        ipv4_address: 10.5.0.5