Include /etc/apache2/uid.conf

Include /etc/apache2/server-tuning.conf

Include /etc/apache2/sysconfig.d/loadmodule.conf

Include /etc/apache2/listen.conf


ErrorLog /var/log/apache2/error_log


Include /etc/apache2/mod_log_config.conf

Include /etc/apache2/sysconfig.d/global.conf

Include /etc/apache2/mod_status.conf
Include /etc/apache2/mod_info.conf

Include /etc/apache2/mod_usertrack.conf

Include /etc/apache2/mod_autoindex-defaults.conf

TypesConfig /etc/apache2/mime.types
#DefaultType text/plain
Include /etc/apache2/mod_mime-defaults.conf

Include /etc/apache2/errors.conf

Include /etc/apache2/ssl-global.conf

<Directory />
    Options None
    AllowOverride None
    Order deny,allow
    Deny from all
</Directory>

AccessFileName .htaccess
# and never show them
<Files ~ "^\.ht">
    Order allow,deny
    Deny from all
</Files>

DirectoryIndex index.html index.html.var

Include /etc/apache2/default-server.conf

Include /etc/apache2/sysconfig.d/include.conf

Include /etc/apache2/vhosts.d/*.conf

AddDefaultCharset UTF-8

#Include /usr/local/apache2/conf/confixx_vhosts/*.conf
Include /usr/local/apache2/conf/mod_security2.conf
