NameVirtualHost 85.10.203.14:80

<Directory "/home/www/web1/html/myhoststar">
#  Options -FollowSymLinks -SymLinksIfOwnerMatch
  <IfModule mod_access.c>
    Allow from all
    Order Deny,Allow
  </IfModule>
#  php_admin_flag engine on
</Directory>


<VirtualHost 85.10.203.14:80>
  ServerName my.hoststar.ch
  ServerAlias www.my.hoststar.ch 
  DocumentRoot /home/www/web1/html/myhoststar
  ScriptAlias /cgi-bin/ /home/www/web1/html/cgi-bin/
<Directory "/home/www/web1/html/myhoststar">
   <IfModule mod_access.c>
    Allow from all
    Order Deny,Allow
  </IfModule>
</Directory>
#  SuexecUserGroup web1 web1

#  php_admin_value open_basedir /home/www/web1/html/:/home/www/web1/phptmp/:/home/www/web1/files/:/home/www/web1/atd/
#  php_admin_value file_uploads 1
#  php_admin_value upload_tmp_dir /home/www/web1/phptmp/
#
#  php_admin_flag register_globals on
#  php_admin_flag magic_quotes_gpc on
#  php_admin_flag safe_mode off
#  php_admin_value safe_mode_exec_dir /home/www/empty/
#  php_admin_flag allow_call_time_pass_reference on
#  php_admin_value memory_limit 64M
#  php_admin_value upload_max_filesize 8M
#  php_admin_value open_basedir /home/www/web1/:/usr/bin:/usr/local/saferpay:/home/www/empty:/tmp
#  php_admin_value session.save_path /home/www/web1/phptmp
#  php_admin_value max_execution_time 300
</VirtualHost>

