version: '3.3'

services:
  ################################################
  crm-test-apache:
    build:
      context: ./config/apache
      dockerfile: Dockerfile
    container_name: crm-test-apache
    restart: unless-stopped
    ports:
      - ${APACHE_INTERNAL_HTTP_PORT}:80
      - ${APACHE_INTERNAL_HTTPS_PORT}:443
