#This ruleset is only available to Atomic Secured Linux and
#Atomicorp Real Time Modsecurity Rules customers.
#
#You can download your copy from our website at the URL below:
#
#https://www.atomicorp.com/products.html
#
#All our products come with a free, no obligation 30 day trial.
