Include includes/loadmodule.conf

Include includes/uid.conf

Include includes/listen.conf

Include includes/server-tuning.conf

Include includes/log-config.conf

Include includes/global.conf

Include mods/mod_status.conf
Include mods/mod_info.conf
Include mods/mod_usertrack.conf
Include mods/mod_autoindex-defaults.conf
Include mods/mod_mime-defaults.conf
Include mods/mod_php5.conf
Include mods/mod_cgid-timeout.conf
Include mods/mod_security2.conf
Include /usr/local/apache2/conf/mod_security2.conf

Include includes/errors.conf

Include includes/ssl-global.conf

Include default-server.conf

## VHOSTS ##
Include vhosts/*.conf
#Include /usr/local/apache2/conf/confixx_vhosts/*.conf
