Include /etc/apache2/includes/loadmodule.conf

Include /etc/apache2/includes/uid.conf

Include /etc/apache2/includes/listen.conf

Include /etc/apache2/includes/server-tuning.conf

Include /etc/apache2/includes/log-config.conf

Include /etc/apache2/includes/global.conf

Include /etc/apache2/includes/mod_status.conf
Include /etc/apache2/includes/mod_info.conf
Include /etc/apache2/includes/mod_usertrack.conf
Include /etc/apache2/includes/mod_autoindex-defaults.conf
Include /etc/apache2/includes/mod_mime-defaults.conf

Include /etc/apache2/includes/errors.conf

Include /etc/apache2/includes/ssl-global.conf

Include /etc/apache2/includes/php5.conf


<Directory />
	Options FollowSymLinks
	AllowOverride All
	Require all denied
</Directory>

AccessFileName .htaccess
# and never show them
<Files ~ "^\.ht">
    Order allow,deny
    Deny from all
</Files>


<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

DirectoryIndex index.html index.html.var




#DocumentRoot /var/www/html

IncludeOptional vhosts/*.conf
