#Define Host_IP "10.5.0.6"
####################################################################
## APACHE_WEB_HOST_IP_LISTEN, APACHE_HTTP_PORT, APACHE_HTTPS_PORT ##
## should be determined in .env file for docker-compose.yml       ##
####################################################################
Define Host_IP ${APACHE_WEB_HOST_IP_LISTEN}
Define Host_Port_HTTP ${APACHE_HTTP_PORT}
Define Host_Port_HTTPS ${APACHE_HTTPS_PORT}


Listen ${Host_Port_HTTP}

#<IfDefine SSL>
#<IfDefine !NOSSL>
<IfModule ssl_module>
	Listen ${Host_Port_HTTPS}
</IfModule>
<IfModule mod_gnutls.c>
	Listen ${Host_Port_HTTPS}
</IfModule>
#</IfDefine>
#</IfDefine>